# Config 
title: Vault
subtitle: By Rene Fekkes
logo: "/assets/images/bio-photo.jpg"
email: henricus.fekkes@gmai.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#twitter_username: username
github_username: Fekko
minimal_mistakes_skin: "dark" #"dirt" #,"default", "air", "aqua", "contrast", "neon", "mint", "plum", "sunrise"
search: true

atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: 

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rene Fekkes"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  location: "Europe"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Fekko"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Fekko"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false

# Code
enable_copy_code_button: true

# Breadcrumbs
breadcrumbs: true  # disabled by default

collections:
  docs:
    output: true
    permalink: /:collection/:path/